apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-application
  template:
    metadata: 
      labels:
        app: nginx-application
    spec: 
      containers:
        - name: nodejs
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-backend
spec:
  selector: 
    app: nginx-application
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  # type: ClusterIp
  